services:
  postgres:
    image: postgres:16-alpine
    container_name: hcm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hcm_journey
    ports:
      - "5433:5432"
    volumes:
      - hcm_pg_data:/var/lib/postgresql/data

volumes:
  hcm_pg_data:
